version: '3.8'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes: 
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db

  redis:
    image: redis
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./todo-backend/redis_data:/data

  server:
    image: todo-backend-nginx
    build:
      context: ./todo-backend/
      dockerfile: Dockerfile
    depends_on:
      - mongo
      - redis
    volumes:
      -  node_modules_server:/usr/src/app/node_modules
    environment: 
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
    container_name: todo-backend-nginx

  app:
    image: todo-frontend-nginx
    build:
      context: ./todo-frontend/
      dockerfile: Dockerfile
    volumes:
      - node_modules_app:/usr/src/app/node_modules
    container_name: todo-frontend-nginx

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:      
      - app
      - server

volumes:
  mongo_data:
  node_modules_server:
  node_modules_app: